create table news
(
    id   int auto_increment
        primary key,
    date datetime    null,
    name varchar(50) null,
    new  text        null
);

INSERT INTO `default`.news (id, date, name, new) VALUES (1, '2022-05-22 19:07:08', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (2, '2022-05-22 19:16:19', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (3, '2022-05-22 19:16:50', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (4, '2022-05-22 19:16:19', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (5, '2022-05-22 19:16:50', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (6, '2022-05-22 19:16:50', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (7, '2022-05-22 19:16:50', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (8, '2022-05-22 19:16:50', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (9, '2022-05-22 19:16:50', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (10, '2022-05-22 19:16:50', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (11, '2022-05-22 19:16:50', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (12, '2022-05-22 19:16:50', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (13, '2022-05-22 19:16:50', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (14, '2022-05-22 19:16:50', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (15, '2022-05-22 19:16:50', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (16, '2022-05-23 13:12:57', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (17, '2022-05-23 13:13:18', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (18, '2022-05-23 13:13:30', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (19, '2022-05-23 13:13:36', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (20, '2022-05-23 13:16:01', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (27, '2022-05-23 16:29:00', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
INSERT INTO `default`.news (id, date, name, new) VALUES (28, '2022-05-23 16:29:13', 'Новость о жизни', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et finibus diam. Pellentesque eu tincidunt risus, vel tempus nibh. Sed feugiat nisl in consectetur aliquam. Quisque fermentum sed dui bibendum pharetra. Etiam at pellentesque eros. Aenean posuere dolor a diam rhoncus placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ornare magna ut vulputate fringilla. Suspendisse turpis lacus, vehicula at diam tincidunt, tristique sollicitudin risus. In vel condimentum libero. Mauris sagittis id neque vel sodales. Suspendisse vitae mi vel nunc egestas consequat quis sit amet nisi. Curabitur non sem et diam efficitur venenatis a ac ipsum. Duis at neque vitae nunc dapibus euismod.

Curabitur nec velit turpis. Donec sed vehicula elit. Fusce auctor leo vitae urna ornare laoreet. Maecenas hendrerit ornare ipsum, non semper diam interdum nec. Curabitur sagittis ipsum et nibh venenatis elementum. Donec sit amet vulputate tellus. Mauris malesuada nisi et turpis tincidunt consequat. Proin lacinia, nunc non venenatis varius, orci ante porta odio, nec mollis justo diam maximus leo. Morbi hendrerit lorem id lacinia placerat. Nulla at fringilla enim.

Etiam malesuada, libero vitae congue molestie, elit augue faucibus ipsum, sit amet viverra purus nunc ut tellus. Morbi vestibulum magna ut mollis pharetra. Sed eget augue dignissim, interdum eros ac, sollicitudin velit. Donec ornare auctor ipsum, et porttitor lacus mollis eget. Sed quis urna et est commodo efficitur. Donec felis nisl, sagittis ut laoreet vitae, fringilla id orci. Donec quis velit tincidunt, venenatis massa ut, aliquam augue. Ut egestas, metus sit amet dapibus lobortis, orci est fringilla odio, eget pulvinar ex ligula eu eros. Nam ac nulla blandit, pharetra nisl sit amet, tincidunt nisi. Donec cursus mauris vel iaculis fermentum.

Sed non risus efficitur, convallis nisl non, venenatis ex. In hac habitasse platea dictumst. Pellentesque ac efficitur urna. Pellentesque volutpat ex at quam convallis accumsan. Quisque ac egestas nisi, a mattis odio. Phasellus gravida, lacus eget tincidunt egestas, tellus neque tristique diam, in placerat augue erat in lectus. Curabitur gravida lacus in luctus ullamcorper. Nunc vitae ipsum nec neque congue pretium in ut urna. Integer nec tortor eu lacus bibendum dapibus eget luctus ex. Aenean neque elit, semper sed vestibulum quis, faucibus vitae tortor. Nulla vulputate felis vitae dignissim faucibus. Praesent rutrum molestie nisl, id molestie lacus pharetra vel. In hac habitasse platea dictumst. Mauris placerat lorem est, in elementum tortor dictum vitae. Duis et nulla sed dolor tempus fringilla.

Proin eleifend massa ac consequat mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus iaculis tincidunt massa, sed tristique enim elementum eget. Morbi ultricies venenatis eleifend. Mauris finibus lorem non arcu maximus aliquam. Sed sit amet enim sodales lorem commodo rhoncus. Fusce ante libero, aliquet et diam sit amet, sodales volutpat arcu. sdfsdfsd fsdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdfsd sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdfsdf sdfsdf sdfsdfsdf sdfsdfsdfsdf sdfsdfsdf sdfsdf sdf sdf');
