version: '3'
networks:
  backend:
volumes:
  mariadb_data:
services:
  nginx:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./:/var/www
      - ./logs/nginx:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - php
    networks:
      - backend
  php:
    build: ./images/php
    volumes:
      - ./:/var/www
    links:
      - mariadb
    networks:
      - backend
  mariadb:
    image: docker.io/bitnami/mariadb:10.5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=nat
      - MARIADB_DATABASE=default
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - backend
    ports:
      - "3306:3306"